[package]
name = "substrate-gen"
version = "0.1.0"
edition = "2021"

[build-dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
    "chain-error",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
framenode-runtime = { path = "../../runtime", default-features = false, features = [
    "std",
    "private-net",
] }
hex = "0.4.3"
sp-core = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.31", default-features = false }

[dependencies]
common = { path = "../../common" }
subxt = "0.24.0"
codec = { package = "parity-scale-codec", version = "3", features = ["derive"] }
scale-info = { version = "2", features = ["derive"] }
bridge-types = { git = "https://github.com/sora-xor/sora2-common", branch = "develop" }
bridge-common = { git = "https://github.com/sora-xor/sora2-common.git", branch = "develop", default-features = false }
beefy-light-client = { git = "https://github.com/sora-xor/sora2-common.git", branch = "develop", default-features = false }
beefy-primitives = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.31" }
jsonrpsee = { version = "0.15.1", features = [
    "macros",
    "ws-client",
    "http-client",
] }
sp-core = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.31", default-features = false }
sp-runtime = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.31", default-features = false }
async-trait = "0.1.49"
serde = { version = "1.0.137", features = ["derive"] }
