[package]
edition = '2018'
name = 'dex-api-benchmarking'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-arithmetic = { version = "2.0.0", default-features = false }
common = { path = "../../../common", default-features = false }
assets = { path = "../../assets", default-features = false }
dex-api = { path = "../../dex-api", default-features = false }
dex-manager = { path = "../../dex-manager", default-features = false }
pool-xyk = { path = "../../pool-xyk", default-features = false }
permissions = { path = "../../permissions", default-features = false }
trading-pair = { path = "../../trading-pair", default-features = false }
technical = { path = "../../technical", default-features = false }

hex-literal = { version = "0.3.1" }

[dev-dependencies]
sp-io = { version = "2.0.0", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
currencies = { version = "0.3.2", package = "orml-currencies", default-features = false }
tokens = { version = "0.3.2", package = "orml-tokens", default-features = false }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'frame-benchmarking/std',
    'sp-std/std',
    'sp-runtime/std',
    'common/std',
    'assets/std',
    'dex-api/std',
    'pool-xyk/std',
    'permissions/std',
    'trading-pair/std',
    'technical/std',
]
