[package]
edition = '2021'
description = "Crate for Demeter Farming Platform benchmarking."
authors = [
    "Danijel Radulovic Ltd. <danijel.radulovic@cerestoken.io>, Jovan Milosevic <jovan.milosevic@cerestoken.io>",
]
license = "BSD-4-Clause"
homepage = "https://cerestoken.io"
repository = "https://github.com/sora-xor/sora2-network"
name = "demeter-farming-platform-benchmarking"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
frame-benchmarking = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false, optional = true }
frame-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
frame-system = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-runtime = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-core = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
common = { path = "../../../common", default-features = false }
ceres-liquidity-locker = { path = "../../ceres-liquidity-locker", default-features = false }
demeter-farming-platform = { path = "../../demeter-farming-platform", default-features = false }
permissions = { path = "../../permissions", default-features = false }
pswap-distribution = { path = "../../pswap-distribution", default-features = false }
multicollateral-bonding-curve-pool = { path = "../../multicollateral-bonding-curve-pool", default-features = false }
dex-manager = { path = "../../dex-manager", default-features = false }
vested-rewards = { path = "../../vested-rewards", default-features = false }
trading-pair = { path = "../../trading-pair", default-features = false }
technical = { path = "../../technical", default-features = false }
pallet-timestamp = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
hex-literal = "0.4.1"

[dev-dependencies]
assets = { path = "../../assets" }
common = { path = "../../../common", features = ["test"] }
ceres-liquidity-locker = { path = "../../ceres-liquidity-locker" }
sp-io = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }
pallet-balances = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }
currencies = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-currencies" }
tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-tokens" }
vested-rewards = { path = "../../vested-rewards" }
permissions = { path = "../../permissions" }
technical = { path = "../../technical" }
pool-xyk = { path = "../../pool-xyk" }
pswap-distribution = { path = "../../pswap-distribution" }
multicollateral-bonding-curve-pool = { path = "../../multicollateral-bonding-curve-pool" }
dex-manager = { path = "../../dex-manager" }

[features]
default = ["std"]
std = [
    'codec/std',
    'common/std',
    'scale-info/std',
    'frame-support/std',
    'frame-system/std',
    'frame-benchmarking/std',
    'sp-std/std',
    'sp-core/std',
    'common/std',
    'assets/std',
    'ceres-liquidity-locker/std',
    'technical/std',
    'trading-pair/std',
    'permissions/std',
    'pool-xyk/std',
]

runtime-benchmarks = [
    "common/runtime-benchmarks",
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
