[package]
edition = '2021'
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
name = 'xst'
version = '1.0.1'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']
rustdoc-args = ["--html-in-header", "misc/docs-katex-header.html"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
currencies = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-currencies", default-features = false }
frame-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
frame-system = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
hex-literal = { version = "0.4.1" }
serde = { version = "1.0.101", default-features = false, optional = true, features = [
    "derive",
] }
sp-arithmetic = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-runtime = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-core = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-tokens", default-features = false }
common = { path = "../../common", default-features = false }
dex-api = { path = "../dex-api", default-features = false }
permissions = { path = "../permissions", default-features = false }
pswap-distribution = { path = "../pswap-distribution", default-features = false }
technical = { path = "../technical", default-features = false }
trading-pair = { path = "../trading-pair", default-features = false }
pool-xyk = { path = "../pool-xyk", default-features = false }
price-tools = { path = "../price-tools", default-features = false }
pallet-timestamp = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }

[dev-dependencies]
ceres-liquidity-locker = { path = "../ceres-liquidity-locker" }
demeter-farming-platform = { path = "../demeter-farming-platform" }
hex-literal = "0.4.1"
pallet-balances = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
pallet-identity = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-core = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-io = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
common = { path = "../../common", features = ["test"] }
dex-manager = { path = "../dex-manager" }
mock-liquidity-source = { path = "../mock-liquidity-source" }
price-tools = { path = "../price-tools" }
technical = { path = "../technical" }
trading-pair = { path = "../trading-pair" }
band = { path = "../band" }
assets = { path = "../assets" }
oracle-proxy = { path = "../oracle-proxy" }

[features]
default = ['std']
std = [
    'codec/std',
    "scale-info/std",
    'currencies/std',
    'frame-support/std',
    'frame-system/std',
    'serde',
    'sp-arithmetic/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-core/std',
    'tokens/std',
    'pool-xyk/std',
    'pallet-timestamp/std',
    'trading-pair/std',
    'technical/std',
    'permissions/std',
    'dex-api/std',
    'common/std',
]

try-runtime = ["frame-support/try-runtime"]
