[package]
name = "trading-pair-rpc"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
sp-runtime = { version = "3", default-features = false }
sp-api = { version = "3", default-features = false }
sp-blockchain = { version = "3", default-features = false }
sp-std = { version = "3", default-features = false }
sp-core = { version = "3", default-features = false }
sp-rpc = { version = "3", default-features = false }
trading-pair-runtime-api = { path = "../runtime-api" }
common = { path = "../../../common" }
