[package]
edition = "2021"
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"
name = "parse"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
    "chain-error",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
framenode-runtime = { path = "../../runtime" }
hex = "0.4.3"
rustc-hex = "2.1.0"

[features]
private-net = ["framenode-runtime/private-net"]
