[package]
name = "bridge-types"
version = "0.1.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2021"

[dependencies]
common = { path = "../../../common", default-features = false }
enum-iterator = "0.6.0"
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
ethbloom = { version = "0.12.1", default-features = false, features = [
	"rlp",
	"codec",
] }
ethereum-types = { version = "0.13.1", default-features = false, features = [
	"codec",
	"rlp",
	"serialize",
] }
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }
hex-literal = { version = "0.3.1", default-features = false }
libsecp256k1 = { version = "0.7", default-features = false }
parity-bytes = { version = "0.1.2", default-features = false }
rlp = { version = "0.5", default-features = false }
serde = { version = "1.0.101", optional = true }
getrandom = { version = "0.2.1", features = ["js"] }

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22", default-features = false }
beefy-primitives = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22", default-features = false }

ethabi = { git = "https://github.com/vovac12/ethabi.git", branch = "polkadot-v0.9.22", package = "ethabi", default-features = false, features = [
	"alloc",
] }
ethash = { git = "https://github.com/vovac12/ethash", branch = "polkadot-v0.9.22-no-std", default-features = false }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.19"
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["std"]
expensive_tests = []
test = ["serde_json"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"ethabi/std",
	"ethbloom/std",
	"ethereum-types/std",
	"hex/std",
	"libsecp256k1/std",
	"parity-bytes/std",
	"rlp/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"beefy-primitives/std",
	"common/std",
]

runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
