[package]
edition = '2018'
name = 'iroha-migration'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
hex = { version = "0.4.2", default-features = false }
serde = { version = "1.0.101", default-features = false, optional = true, features = ["derive"] }
sha3 = { version = "0.9.1", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
pallet-multisig = { version = "2.0.0", default-features = false }

# Git dependencies
ed25519-dalek-iroha = { git = "https://github.com/soramitsu/sora2-ed25519-dalek-iroha.git", branch = "develop", default-features = false, features = ["u64_backend"] }

# Path dependencies
assets = { path = "../assets", default-features = false }
referral-system = { path = "../referral-system", default-features = false }
technical = { path = "../technical", default-features = false }
common = { path = "../../common", default-features = false }

[dev-dependencies]
sp-core = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
parity-util-mem = { version = "0.7.0", default-features = false }

# Required by assets
currencies = { version = "0.3.2", package = "orml-currencies", default-features = false }
tokens = { version = "0.3.2", package = "orml-tokens", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
permissions = { path = "../permissions", default-features = false }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'assets/std',
    'referral-system/std',
    'technical/std',
    'common/std',
    'pallet-multisig/std',
    'serde',
]
