[package]
name = "migration-app"
version = "0.1.1"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { version = "3", package = "parity-scale-codec", default-features = false, features = [
  "derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }
rlp = { version = "0.5.2", default-features = false }
hex-literal = { version = "0.3.1", default-features = false }

frame-benchmarking = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false, optional = true }
frame-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
frame-system = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-core = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-io = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-runtime = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }

ethabi = { git = "https://github.com/sora-xor/ethabi.git", branch = "sora-v1.6.0", package = "ethabi", default-features = false }

bridge-types = { git = "https://github.com/sora-xor/sora2-common.git", default-features = false }

assets = { path = "../../assets", default-features = false }
traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-traits", default-features = false }
technical = { path = "../../technical", default-features = false }
permissions = { path = "../../permissions", default-features = false }
common = { path = "../../../common", default-features = false }
dispatch = { git = "https://github.com/sora-xor/sora2-common.git", default-features = false, optional = true }

eth-app = { path = "../eth-app", default-features = false }
erc20-app = { path = "../erc20-app", default-features = false }

[dev-dependencies]
dispatch = { git = "https://github.com/sora-xor/sora2-common.git" }
sp-keyring = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }
pallet-balances = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }
tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-tokens" }
traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-traits" }
common = { path = "../../../common", features = ["test"] }
currencies = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-currencies" }

[features]
default = ["std"]
std = [
  "eth-app/std",
  "erc20-app/std",
  "serde",
  "hex/std",
  "codec/std",
  "scale-info/std",
  "frame-support/std",
  "frame-system/std",
  "sp-core/std",
  "sp-std/std",
  "sp-io/std",
  "sp-runtime/std",
  "bridge-types/std",
  "ethabi/std",
  "rlp/std",
  "assets/std",
  "technical/std",
  "traits/std",
  "permissions/std",
  "common/std",
  "eth-app/std",
  "erc20-app/std",
]

runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "dispatch/runtime-benchmarks",
]

try-runtime = [
    "frame-support/try-runtime",
]
